export const tableConfigs: {
  [key: string]: { label: string; endpoint: string };
} = {
  category: { label: "Categories", endpoint: "/api/category" },
  "expense-status": { label: "Expense Status", endpoint: "/api/expenseStatus" },
  "subscription-status": {
    label: "Subscription Status",
    endpoint: "/api/subscriptionStatus",
  },
  "invoice-status": {
    label: "Invoice Status",
    endpoint: "/api/invoiceStatus",
  },
  customers: { label: "Customers", endpoint: "/api/customer" },
  addresses: { label: "Addresses", endpoint: "/api/address" },
  "service-price": { label: "Service Prices", endpoint: "/api/servicePrice" },
  invoice: { label: "Invoices", endpoint: "/api/invoice" },
  expense: { label: "Expenses", endpoint: "/api/expense" },
  "print-material": {
    label: "Print Materials",
    endpoint: "/api/printMaterial",
  },
  "print-job": { label: "Print Jobs", endpoint: "/api/printJob" },
  project: { label: "Projects", endpoint: "/api/project" },
  task: { label: "Tasks", endpoint: "/api/task" },
  "time-log": { label: "Time Logs", endpoint: "/api/timeLog" },
  subscription: { label: "Subscriptions", endpoint: "/api/subscription" },
};

// Updated fallback keys for creating/editing records.
export const fallbackKeys: Record<string, string[]> = {
  category: ["name"],
  "expense-status": ["status"],
  "subscription-status": ["status"],
  "invoice-status": ["status"],
  customers: ["firstname", "lastname", "email", "phone"],
  addresses: [
    "street",
    "number",
    "city",
    "state",
    "country",
    "zipCode",
    "customerId",
  ],
  "service-price": ["categoryId", "service", "price"],
  invoice: ["invoiceDate", "amount", "statusId", "customerId", "priceId"],
  expense: [
    "neededAt",
    "name",
    "link",
    "image",
    "unitPrice",
    "quantity",
    "approved",
    "recurring",
    "recurringInterval",
    "approvedAt",
    "orderedAt",
    "statusId",
    "customerId",
  ],
  "print-material": [
    "type",
    "subType",
    "stock",
    "color",
    "unitPrice",
    "unitAmount",
  ],
  "print-job": [
    "name",
    "scheduledDate",
    "ordered",
    "completed",
    "quantity",
    "printTime",
    "weight",
    "customerId",
    "priceId",
    "materialId",
    "invoiceId",
  ],
  project: ["name", "parentProjectId", "customerId", "priceId", "invoiceId"],
  task: ["title", "description", "userId", "done", "categoryId", "projectId"],
  "time-log": ["projectId", "startTime", "endTime", "user", "printJobId"],
  subscription: [
    "name",
    "link",
    "image",
    "unitPrice",
    "quantity",
    "interval",
    "customerId",
    "statusId",
  ],
};

export default () => null;
